workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      node: 18
      vars:
        EXPO_TOKEN: ${{ inputs.EXPO_TOKEN }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ inputs.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ inputs.APP_STORE_CONNECT_KEY_IDENTIFIER }}
        APP_STORE_CONNECT_PRIVATE_KEY: ${{ inputs.APP_STORE_CONNECT_PRIVATE_KEY }}
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install && cd ..
      - name: Build iOS app
        script: |
          npx eas build --platform ios --profile production --non-interactive
    artifacts:
      - build/**/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: true
