workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      node: 18
      vars:
        EXPO_TOKEN:   5aoR40okvqTbsm-cNAsn0zLWgSnWmZrEhuFA2TWt
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(bcfc7865-be78-4ecc-96a4-105545e81432)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(356DVBD4XP)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # Remplacez par le contenu de votre fichier .p8
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install && cd ..
      - name: Build iOS app
        script: |
          npx eas build --platform ios --profile production --non-interactive
    artifacts:
      - build/**/*.ipa
    publishing:
      app_store_connect:
        auth: api_key
        submit_to_testflight: false
        submit_to_app_store: true
